### PR TITLE
Initial checkin of ManagedBookmarks

### PR DESCRIPTION
**Pull request by mkaply**
This isn't ready to checkin, but want to make it available for folks to see.

### CODE REVIEW

**Comment by Peter-Gajdek** [comment]
the "maxLength="2048" might need to be bumped up to 4096 at least if you want to have couple folders and more than 1 or 2 bookmarks inside them.. our json file is close to 3500 so I had to edit it manually on our systems to test it

**Comment by mkaply** [comment]
I don't know why I put that in. I'll bump.

> the only thing it puts it on far right on the toolbar.. which is better than nothing.

It should put it on the far left. Can you try a new profile?

I'll take a look.

**Comment by robtherobot85** [comment]
I have tested this out on a couple of PCs and it works.  I too had the issue with the maxLength=2048.  Our work bookmarks is a little under 7000 in length so I set mine to 8192.  On both PCs it went to the right instead of the left.  If you create a new profile it is on the left.  Thanks

**Comment by mkaply** [comment]
I just tested with existing profiles and I can't get it to appear on the right.

What's odd is that the code explicitly puts it at location 0 if it's not there already. So for some reason it must already be there?

https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#2181

I'm at a loss.

**Comment by Peter-Gajdek** [comment]
in our case we used the other GPO option for bookmarks prior to this (the one where you set 1 bookmark per option)... i've cleared the registry entries thinking that was interfering but made no difference.. and I tried new profile and was showing on right as well

**Comment by mkaply** [comment]
That helps a lot. Can you get me the value of browser.uiCustomization.state in the case where it puts it on the right? That will help me debug.

**Comment by Peter-Gajdek** [comment]
`user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"search-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"gmailnoads_mywebber_com-browser-action\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\",\"managed-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-niffy2ca8fy1tg_jetpack-browser-action\",\"_75afe46a-7a50-4c6b-b866-c43a1075b071_-browser-action\",\"gmailnoads_mywebber_com-browser-action\",\"feed-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");`

**Comment by mkaply** [comment]
Well that's interesting. managed-bookmarks is clearly after personal-bookmarks (so it already existed for some reason)

This was in a profile that hadn't had managed bookmarks yet?

**Comment by Peter-Gajdek** [comment]
this was off profile using the old method to manage bookmarks.. the list 1 thru 51 individual options in GPO

**Comment by mkaply** [comment]
So I think I know what's going on here (and one of the reasons I didn't make this 100% public on release).

For 83 I switched to a more dynamic version of the button and I think it doesn't have this problem.

But the old button somehow got added. I'm looking at how to remediate.

**Comment by mkaply** [comment]
There still might be cases where button ends up on the right. I'm still investigating.

**Pull request merged**
