### PR TITLE
Add `temporarily_allow_weak_signatures` to `ExtensionSettings`

### PR DESCRIPTION
**Pull request by willdurand**

### CODE REVIEW

**Comment by willdurand** [comment]
cc @mkaply

**Comment by mkaply** [comment]
I thought this was in 126 per:

https://bugzilla.mozilla.org/show_bug.cgi?id=1885652

**Comment by willdurand** [comment]
Most of the work landed in 126, yes, but the restriction will only be enabled in 127 as per https://bugzilla.mozilla.org/show_bug.cgi?id=1886160

**Comment by willdurand** [comment]
Are we good, @mkaply?

**Comment by mkaply** [comment]
Yep. Once I ship policy this week, I'll merge all of this.

**Pull request merged**
