### PR TITLE
Add documentation for DisableEncryptedClientHello

### PR DESCRIPTION
**Pull request by dennisjackson**
Companion to [D207436](https://phabricator.services.mozilla.com/D207436)

### CODE REVIEW

**Comment by mkaply** [comment]
This will merge after 126 ships.

**Comment by mkaply** [comment]
Hey Dennis, you accidentally duplicated the DisableDeveloperTools policy :).
Can you update?
If not, I'll just do a new patch.
Thanks!

**Comment by dennisjackson** [comment]
Oops, fixed!

**Comment by mkaply** [comment]
Thanks!

**Pull request merged**
