### PR TITLE
Policy for Proxy settings. Fixes #19.

### LINKED ISSUE #19: Support policy on GPO: Proxy
From https://bugzilla.mozilla.org/show_bug.cgi?id=1429177

### PR DESCRIPTION
**Pull request by mkaply**
This will definitely need some review.

### CODE REVIEW

**Comment by mkaply** [comment]
Here's how the UI ended up having to look.

Any entry field on a given section is mandatory, so to have optional entry fields, each had to be on their own page

So you select the proxy mode and then fill out the right section. (This is how chrome does it as well)

image

**Comment by mkaply** [comment]
@felipec

**Comment by felipc** [comment]
I'll take a look

**Comment by mkaply** [comment]
Here's what it looks like now

image

**Pull request merged**
