### PR TITLE
Fixed Bookmarks (Might no Longer be Applicable)

### PR DESCRIPTION
**Pull request by jeffreymcclain**
I think you already added your own fix, but just in case it helps, I think I figured out a solution yesterday.

I changed every tenth registry key to be a single digit (20 becomes 3, 30 becomes 4, etc). This prevents any individual policies from the initial release from leaving orphaned registry keys that could cause issues, while also maintaining the order in both the group policy editor and Windows registry (1, 12, 13, 14, ..., 19, 2, 21, 22, ..., 28, 29, 3, 31, etc) which ensures a folder with lots of bookmarks remains in the expected order.

### CODE REVIEW

**Comment by jeffreymcclain** [comment]
@mkaply , sorry to keep bothering you about this, but have you decided on the final number (and numbering scheme) for the bookmarks policies? If you don't plan to use my implementation that's perfectly fine, I'd just like to know what the official implementation will be, so I can hopefully begin a wider rollout at my company.

I looked over the code for the current v1.2 release, and one thing I noticed is the registry key numbering is in numerical rather than alphabetical order (Windows uses alphabetical for some reason). This means bookmarks will not populate in the order people expect.

Based on my testing with your implementation, if all the bookmarks were to be placed in the same folder, the order from top to bottom in the folder would be (Bookmark 1,  Bookmark_10, Bookmark_11, Bookmark_12, Bookmark_13 ... Bookmark 2, Bookmark 20, Bookmark 3, etc) due to the corresponding registry keys being alphabetized (1, 10, 11, 12, 13, ... , 2, 20, 3) which is a bit confusing.

Your underscore solution works for the alphabetical order WITHIN the group policy editor itself, but not for the actual ordering of bookmarks as they will appear to end users.

**Comment by mkaply** [comment]
Argh. I'll do some more testing. I had GPO.

**Comment by mkaply** [comment]
I HATE gpo. Not had :)

**Comment by jeffreymcclain** [comment]
@mkaply 
I recall you mentioning your primary concern was orphaned registry keys with people who used earlier versions of the group policy implementation (either v1.0 or v1.2 at this point).

I ran into the same issue, and I just want to be clear that it is relatively easy for us to fix / workaround (though the code will look a bit messy). Essentially, this issue only occurs if we push an updated admx / adml file with MISSING registry keys that were present in a previous version. 

So far you have released:
v1.0 keys: 1, 2, 3, 4, 5 [1-5]
v1.2 keys: 1, 2, 3, ..., 19, 20 [1-20]

This means that in order to maintain backwards compatibility without breaking anything, these keys will ALWAYS have to be defined in all future versions. The update I submitted a pull request for at the top of this thread [1,11, 12, .., 19, **2**, 21, ... 48, 49, **5**] would make my code backwards compatible with v1.0, unfortunately you've since pushed out a modified V1.2 (including keys 6, 7, 8, and 9) which breaks compatibility again (not blaming you, just explaining). 

However, the good news is I should be able to easily rectify this and submit a pull request to make both the ordering logical (in both group policy editor for IT people and the actual bookmark order being correct for end users). The bad news is that the actual code within the admx file will be increasingly unintuitive, as I will have to force the numbering scheme to respect alphabetical order [1,10,11,12,..2,20,21,...,3,30,31,...4,40,41,42,43,44,5,6,7,8,9]. THis hopefully will be an acceptable tradeoff though, considering the only people looking at the source code will be Mozilla employees / developers anyway, and we can always explain the numbering in the documentation just in case.

**Comment by jeffreymcclain** [comment]
@mkaply just tested and everything seems to be working. Keep in mind, if people upgrade from the older admx / adml files, any older bookmarks will still be configurable (no orphaned registry keys), however the name and number of said bookmarks WITHIN group policy editor will be changed (not the end-user viewing order, just the group policy editor for IT people). 

For example, someone who had configured "Bookmark Five" in v1.0 would now have "Bookmark 45" in my version. Hopefully this is a reasonable compromise, as anyone who has configured an earlier version of the bookmarks can simply scroll through the group policy editor to see which bookmarks are configured (their old bookmarks) and their new mappings. You can test this out if you'd like by intentionally installing an older version of the admx / adml files, configuring the bookmark policies,  updating the admx and adml files, and finally checking the group policy editor again.

Specifically, the mapping is:
Old | New
1 -> 1 (same)
2 -> 12
3-> 23
4-> 34
5 -> 45
6 -> 47
7 -> 48
8 -> 49
9 -> 50
10 -> 2
11 -> 3
12 -> 4
13 -> 5
14 -> 6
15 -> 7
16 ->8
17 -> 9
18 -> 10
19 -> 11
20 -> 13

**Comment by mkaply** [comment]
I think this pull is fine (had to read it a couple times to understand what you did). Clever!

**Pull request merged**
