### PR TITLE
Update firefox.admx

### PR DESCRIPTION
**Pull request by neilmartin83**
Bump minimum required version to 1.2 - fixes error in RSOP regarding version mismatch

### CODE REVIEW

**Comment by neilmartin83** [comment]
9d458972-db50-4d2a-8a2b-4d4b193ddd50

**Comment by mkaply** [comment]
I'll take this, but Windows has a serious bug here. Why is it called minRequiredVersion if that's not what is is?

1.1 is < 1.2 which meets minRequiredVersion :)

**Comment by neilmartin83** [comment]
Yep - silly behaviour on the Windows side - it freaked us out when we first saw the error - the GPO settings etc all appeared fine in the Group Policy Editor before changing this though. Cheers!

**Comment by mkaply** [comment]
And thank you!

**Comment by SecT0uch** [comment]
I have exactly the same issue with the last release. I had to downgrade

**Pull request merged**
