### PR TITLE
Fixed Typos

### PR DESCRIPTION
**Pull request by jeffreymcclain**
I fixed several grammatical errors including misspelled words, missing periods, and incorrect verb tense.

### CODE REVIEW

**Comment by mkaply** [comment]
@jeffreymcclain I'm working on doing a better job with the documentation.

Since you're already doing such a great job on this, would you be interested in helping with that?

**Comment by jeffreymcclain** [comment]
@mkaply I'm interested. I'm actually working on documentation for my company on the Firefox group policy, so I decided to submit pull-requests with my changes in case anyone finds them useful. My manager wants me to document and test the group policy, confirming it's safe and stable before we attempt to roll it out across the organization.

**Comment by mkaply** [comment]
That would be awesome. And I can promise you some Firefox swag.

Basically what I was trying to do (and haven't finished) was put together documentation similar to Chrome:

https://www.chromium.org/administrators/policy-list-3

This is how it was looking:

https://mozilla.github.io/policy-templates/

which is based on:

https://github.com/mozilla/policy-templates/blob/master/index.html

Chrome's stuff is all strings and bools, though so I wasn't sure it all mapped nicely into the format I was trying...

I've opened https://github.com/mozilla/policy-templates/issues/203 to discuss.

**Comment by jeffreymcclain** [comment]
@mkaply Not to be rude / imposing, but is there any chance I could get some of that Firefox swag you mentioned earlier? I know I haven't completed all the documentation yet, but I feel like I contributed a fair amount. 

I'm currently somewhat busy with school and work, but I will hopefully have time over the coming month(s) to help further flesh-out https://mozilla.github.io/policy-templates/

**Comment by mkaply** [comment]
Heck yeah. Send your physical address to mkaply@mozilla.com as well as your shirt size (although I can't promise a shirt). I'll be at the home office next week so I'll get something together.

**Pull request merged**
