### PR TITLE
Add ContentAnalysis policies

### PR DESCRIPTION
**Pull request by gregstoll**
See bug 1887179

### CODE REVIEW

**Comment by mkaply** [comment]
Thanks! I'll land this when it lands in Firefoxl

**Comment by gregstoll** [comment]
Great! [Bug 1869868](https://bugzilla.mozilla.org/show_bug.cgi?id=1869868) is the last piece that should be touching these policies, so I'll let you know when that goes in.

**Comment by gregstoll** [comment]
OK, this just landed in Firefox, so this is ready to merge. Thanks @mkaply!

**Comment by mkaply** [comment]
Thanks! I'll merge after I do a release this week.

**Pull request merged**
